// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjDSUJiXODci-F3vu6EQZiqWVlVscV9s',
    appId: '1:591708297487:web:2b265c4ce2f3e22c12c67a',
    messagingSenderId: '591708297487',
    projectId: 'fir-flutter-login-ccd6c',
    authDomain: 'fir-flutter-login-ccd6c.firebaseapp.com',
    storageBucket: 'fir-flutter-login-ccd6c.firebasestorage.app',
    measurementId: 'G-9BX6Z7YJDH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPb5gQ3O6mZHTTukzRDG1KipBk2qHZA5s',
    appId: '1:591708297487:android:b55061f28026778c12c67a',
    messagingSenderId: '591708297487',
    projectId: 'fir-flutter-login-ccd6c',
    storageBucket: 'fir-flutter-login-ccd6c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvvgCD6QZtH4oE3Fr4ZO2DXv91TrqHvxg',
    appId: '1:591708297487:ios:469a40e51eb069fc12c67a',
    messagingSenderId: '591708297487',
    projectId: 'fir-flutter-login-ccd6c',
    storageBucket: 'fir-flutter-login-ccd6c.firebasestorage.app',
    iosClientId: '591708297487-jdem8ecq7d8ouevnsh6k7e2ujjv0vjnt.apps.googleusercontent.com',
    iosBundleId: 'com.binhnguyen.demoGetxSupabase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvvgCD6QZtH4oE3Fr4ZO2DXv91TrqHvxg',
    appId: '1:591708297487:ios:469a40e51eb069fc12c67a',
    messagingSenderId: '591708297487',
    projectId: 'fir-flutter-login-ccd6c',
    storageBucket: 'fir-flutter-login-ccd6c.firebasestorage.app',
    iosClientId: '591708297487-jdem8ecq7d8ouevnsh6k7e2ujjv0vjnt.apps.googleusercontent.com',
    iosBundleId: 'com.binhnguyen.demoGetxSupabase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZjDSUJiXODci-F3vu6EQZiqWVlVscV9s',
    appId: '1:591708297487:web:f3c7a4222e6bb40812c67a',
    messagingSenderId: '591708297487',
    projectId: 'fir-flutter-login-ccd6c',
    authDomain: 'fir-flutter-login-ccd6c.firebaseapp.com',
    storageBucket: 'fir-flutter-login-ccd6c.firebasestorage.app',
    measurementId: 'G-85BXRDHG7B',
  );
}
